import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Pricing | CreviaCockpit',
  description: 'Try free before you commit. Every tier comes with a trial — longer for deeper tiers.',
};

/* ── Feature list helper ─────────────────────────────────── */
function Check({ color }: { color: string }) {
  return (
    <span style={{
      width: 16, height: 16, borderRadius: '50%', flexShrink: 0, marginTop: 1,
      display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 9,
      background: `${color}1a`, color, border: `1px solid ${color}40`,
    }}>✓</span>
  );
}

interface FeatItemProps {
  color: string;
  label: string;
  note?: string;
  featured?: boolean;
}
function FeatItem({ color, label, note, featured }: FeatItemProps) {
  return (
    <li style={{ display: 'flex', alignItems: 'flex-start', gap: 9, fontSize: 12.5, color: featured ? '#e2e6f0' : '#788098', lineHeight: 1.45 }}>
      <Check color={color} />
      <div>
        {featured ? <strong style={{ color: '#e2e6f0' }}>{label}</strong> : label}
        {note && <div style={{ fontFamily: 'var(--font-mono)', fontSize: 9, color: '#38405a', marginTop: 2 }}>{note}</div>}
      </div>
    </li>
  );
}

/* ── FAQ data ──────────────────────────────────────────────── */
const faqs = [
  {
    q: 'Do I need a credit card to start a trial?',
    a: 'No. All trials start without a credit card. You only add payment details when you decide to continue after the trial period.',
  },
  {
    q: 'Why do deeper tiers get longer trials?',
    a: 'Basic gives you access to the core tools. Premium and Premium+ unlock AI trade setups, whale intelligence, and deeper API access. The longer trials ensure you can experience the full value — especially the features that compound over multiple market cycles.',
  },
  {
    q: 'Can I cancel anytime?',
    a: "Yes — cancel at any time from your account page. No lock-in, no penalty. Beta pricing is locked for the duration of your subscription, but doesn't carry over if you re-subscribe after cancelling.",
  },
  {
    q: 'What makes Premium+ different from Premium?',
    a: 'Premium+ gets you first-hour exclusive access (signals before all other tiers), custom analysis requests for sector deep-dives, and unlimited API calls — built for active traders, funds, and builders who need maximum depth.',
  },
  {
    q: 'Is the AI-generated analysis reliable?',
    a: '78% historical accuracy on regime detection. All content is generated by Claude in the context of the live market regime — not templated. Trade setups are regime-aligned, not generic TA. You still make the final call.',
  },
];

/* ── Comparison table data ─────────────────────────────────── */
const compareRows = [
  { section: 'Analysis & Intelligence' },
  { feat: 'Market regime detection', basic: '✓', premium: '✓', plus: '✓' },
  { feat: 'All 16 assets — live',    basic: '✓', premium: '✓', plus: '✓' },
  { feat: 'Analysis feed',           basic: '6h delay', premium: 'Instant', plus: 'First-hour' },
  { feat: 'AI trade setups',         basic: '—', premium: '✓', plus: '✓' },
  { feat: 'Opportunity scanner',     basic: '—', premium: '✓', plus: '✓' },
  { feat: 'Custom analysis requests',basic: '—', premium: '—', plus: '✓' },
  { section: 'Trading Tools' },
  { feat: 'Risk calculator',         basic: '✓', premium: '✓', plus: '✓' },
  { feat: 'Personalised alerts',     basic: 'Up to 10', premium: 'Unlimited', plus: 'Unlimited' },
  { feat: 'Trade journal',           basic: '—', premium: '✓', plus: '✓' },
  { feat: 'Portfolio sync',          basic: '—', premium: '✓', plus: '✓' },
  { section: 'Whale Intelligence' },
  { feat: 'Whale alerts',            basic: '—', premium: '✓', plus: '✓' },
  { feat: 'Exchange netflow',        basic: '—', premium: '✓', plus: '✓' },
  { feat: 'Composite sentiment',     basic: '—', premium: '✓', plus: '✓' },
  { section: 'Data & API' },
  { feat: 'Historical data',         basic: '7 days', premium: '90 days', plus: 'Unlimited' },
  { feat: 'API access',              basic: '—', premium: '500 calls/day', plus: 'Unlimited' },
  { feat: 'CSV / PDF export',        basic: '—', premium: '✓', plus: '✓' },
  { feat: 'Daily email digest',      basic: '✓', premium: '✓', plus: '✓' },
];

/* ── Page ────────────────────────────────────────────────── */
export default function PricingPage() {
  return (
    <div style={{ background: '#070809', minHeight: '100vh', color: '#e2e6f0' }}>

      {/* ══ HERO ══ */}
      <div className="pricing-hero">
        <div style={{ position: 'absolute', inset: 0, backgroundImage: 'linear-gradient(rgba(0,229,160,0.025) 1px, transparent 1px), linear-gradient(90deg, rgba(0,229,160,0.025) 1px, transparent 1px)', backgroundSize: '60px 60px', maskImage: 'radial-gradient(ellipse 70% 80% at 50% 50%, black 0%, transparent 70%)', WebkitMaskImage: 'radial-gradient(ellipse 70% 80% at 50% 50%, black 0%, transparent 70%)' }} />
        <div style={{ position: 'absolute', top: 0, left: '25%', right: '25%', height: 1, background: 'linear-gradient(90deg, transparent, #00d68f, transparent)' }} />

        <div className="font-mono-cc" style={{ display: 'inline-flex', alignItems: 'center', gap: 7, fontSize: 10, letterSpacing: '1.5px', textTransform: 'uppercase', color: '#00d68f', background: 'rgba(0,214,143,0.07)', border: '1px solid rgba(0,214,143,0.2)', padding: '5px 14px', borderRadius: 20, marginBottom: 24 }}>
          <span style={{ width: 5, height: 5, borderRadius: '50%', background: '#00d68f', animation: 'livePulse 2s ease-in-out infinite' }} />
          Try free before you commit
        </div>

        <h1 className="font-serif-cc pricing-h1" style={{ fontSize: 52, lineHeight: 1.1, letterSpacing: -1, color: '#e2e6f0', marginBottom: 14 }}>
          The cockpit pays for<br /><em style={{ fontStyle: 'italic', color: '#00d68f' }}>itself in one trade.</em>
        </h1>

        <p style={{ fontSize: 15, fontWeight: 300, color: '#788098', maxWidth: 500, margin: '0 auto 32px', lineHeight: 1.7 }}>
          Every tier comes with a free trial — longer trials for deeper tiers, so you experience the full value before spending a cent. The real-time risk calculator and personalised alerts alone are worth the price.
        </p>

        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 10, background: '#10141c', border: '1px solid #222c42', borderRadius: 6, padding: '10px 20px', marginBottom: 48 }}>
          <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#f0a030', animation: 'livePulse 2s ease-in-out infinite' }} />
          <span className="font-mono-cc" style={{ fontSize: 11, color: '#788098' }}>
            <strong style={{ color: '#f0a030' }}>No credit card</strong> required to start your trial
          </span>
          <span style={{ width: 1, height: 14, background: '#222c42' }} />
          <span className="font-mono-cc" style={{ fontSize: 10, letterSpacing: '0.8px', textTransform: 'uppercase', color: '#00d68f', background: 'rgba(0,214,143,0.08)', border: '1px solid rgba(0,214,143,0.2)', padding: '3px 9px', borderRadius: 3 }}>
            Cancel anytime
          </span>
        </div>
      </div>

      {/* ══ TRIAL LADDER ══ */}
      <div className="pricing-section">
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', background: '#10141c', border: '1px solid #1a2030', borderRadius: 8, overflow: 'hidden' }}>
          {[
            { days: '3',  label: 'Day free trial', tier: 'Basic · $20/mo',    color: '#00d68f' },
            { days: '7',  label: 'Day free trial', tier: 'Premium · $100/mo', color: '#f0a030' },
            { days: '14', label: 'Day free trial', tier: 'Premium+ · $200/mo',color: '#9b7cf4' },
          ].map((t, i) => (
            <div key={t.days} style={{ padding: '16px 24px', borderRight: i < 2 ? '1px solid #1a2030' : 'none', display: 'flex', alignItems: 'center', gap: 12 }}>
              <div className="font-bebas" style={{ fontSize: 36, color: t.color, lineHeight: 1 }}>{t.days}</div>
              <div>
                <div className="font-mono-cc" style={{ fontSize: 10, letterSpacing: '1px', textTransform: 'uppercase', color: '#38405a' }}>{t.label}</div>
                <div style={{ fontSize: 12, color: '#788098', marginTop: 2 }}>{t.tier}</div>
              </div>
            </div>
          ))}
        </div>
        <div className="font-mono-cc" style={{ textAlign: 'center', fontSize: 10, color: '#38405a', marginTop: 10 }}>
          Longer trials for deeper tiers — more time to feel the full value before committing.
        </div>
      </div>

      {/* ══ PLANS GRID ══ */}
      <div className="plans-section">
      <div className="plans-grid">

        {/* ── BASIC ── */}
        <div style={{ background: '#10141c', border: '1px solid #1a2030', borderRadius: 8, padding: '28px 24px', display: 'flex', flexDirection: 'column', gap: 20 }}>
          <div>
            <div className="font-mono-cc" style={{ fontSize: 9, letterSpacing: '2px', textTransform: 'uppercase', color: '#38405a', marginBottom: 4 }}>Observer</div>
            <div className="font-bebas" style={{ fontSize: 32, letterSpacing: 1, color: '#e2e6f0', lineHeight: 1 }}>Basic</div>
            <div style={{ display: 'flex', alignItems: 'baseline', gap: 6, marginTop: 6 }}>
              <div className="font-bebas" style={{ fontSize: 44, lineHeight: 1, color: '#e2e6f0' }}>$20</div>
              <div className="font-mono-cc" style={{ fontSize: 11, color: '#38405a' }}>/month</div>
            </div>
            <div className="font-mono-cc" style={{ fontSize: 10, color: '#00d68f', marginTop: 3, marginBottom: 8 }}>
              <span style={{ background: 'rgba(0,214,143,0.08)', border: '1px solid rgba(0,214,143,0.2)', padding: '2px 8px', borderRadius: 3 }}>3-day free trial</span>
            </div>
            <div style={{ fontSize: 12, color: '#788098', lineHeight: 1.6 }}>Core intelligence for traders who want real-time signals without the full depth.</div>
          </div>
          <Link href="/auth/register" className="font-mono-cc" style={{ display: 'block', textAlign: 'center', fontSize: 11, letterSpacing: '0.8px', textTransform: 'uppercase', padding: 12, borderRadius: 5, color: '#788098', background: 'none', border: '1px solid #222c42', textDecoration: 'none' }}>
            Start 3-Day Trial Free →
          </Link>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10 }}>
            <FeatItem color="#00d68f" label="Real-time risk calculator" note="Position sizing · Drawdown · Portfolio exposure" featured />
            <FeatItem color="#00d68f" label="Personalised price alerts" note="Up to 10 custom alerts" featured />
            <FeatItem color="#00d68f" label="Market regime detection" note="Live regime · confidence · action" />
            <FeatItem color="#00d68f" label="All 16 assets — live" />
            <FeatItem color="#00d68f" label="Market dashboard" />
            <FeatItem color="#00d68f" label="Analysis feed" note="6-hour delay on memos & threads" />
            <FeatItem color="#00d68f" label="Weekly email digest" />
          </ul>
          <div className="font-mono-cc" style={{ fontSize: 10, color: '#38405a', textAlign: 'center', paddingTop: 12, borderTop: '1px solid #1a2030' }}>No credit card to start trial</div>
        </div>

        {/* ── PREMIUM (featured) ── */}
        <div style={{ background: '#10141c', border: '1px solid #222c42', borderRadius: 8, position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 2, background: 'linear-gradient(90deg, transparent, #00d68f, transparent)' }} />
          <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 80% 50% at 50% 0%, rgba(0,214,143,0.06) 0%, transparent 60%)', pointerEvents: 'none' }} />
          <div style={{ padding: '32px', display: 'flex', flexDirection: 'column', gap: 20 }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }}>
                <div className="font-mono-cc" style={{ fontSize: 9, letterSpacing: '2px', textTransform: 'uppercase', color: '#00d68f' }}>Pilot</div>
                <span className="font-mono-cc" style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 9, letterSpacing: '0.8px', textTransform: 'uppercase', color: '#00d68f', background: 'rgba(0,214,143,0.08)', border: '1px solid rgba(0,214,143,0.2)', padding: '3px 8px', borderRadius: 3 }}>⚡ Most popular</span>
              </div>
              <div className="font-bebas" style={{ fontSize: 40, color: '#00d68f', lineHeight: 1 }}>Premium</div>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 6, marginTop: 6 }}>
                <div className="font-bebas" style={{ fontSize: 64, lineHeight: 1, color: '#e2e6f0' }}>$100</div>
                <div>
                  <div className="font-mono-cc" style={{ fontSize: 11, color: '#38405a' }}>/month</div>
                  <div className="font-mono-cc" style={{ fontSize: 9, color: '#f0a030', marginTop: 1 }}>7-day free trial</div>
                </div>
              </div>
              <div style={{ fontSize: 13, color: '#788098', lineHeight: 1.6, marginBottom: 20 }}>
                Full cockpit. Real-time intelligence, AI trade setups, whale tracking, and unlimited alerts — everything you need to trade with conviction.
              </div>
              <Link href="/auth/register" className="font-mono-cc" style={{ display: 'block', textAlign: 'center', fontSize: 12, letterSpacing: '0.8px', textTransform: 'uppercase', padding: 14, borderRadius: 5, color: '#08090c', background: '#00d68f', fontWeight: 500, boxShadow: '0 0 24px rgba(0,214,143,0.25)', textDecoration: 'none' }}>
                Start 7-Day Trial Free →
              </Link>
            </div>
            <div>
              <div className="font-mono-cc" style={{ fontSize: 9, letterSpacing: '1.5px', textTransform: 'uppercase', color: '#38405a', marginBottom: 14 }}>Everything in Basic, plus:</div>
              <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10 }}>
                <FeatItem color="#00d68f" label="Unlimited personalised alerts" note="Price · Regime change · Whale movement · Setup fires" featured />
                <FeatItem color="#00d68f" label="AI trade setups — live" note="Entry · TP · SL · R/R · regime-aligned" featured />
                <FeatItem color="#00d68f" label="Whale intelligence" note="Live alerts · Netflow · Composite sentiment" featured />
                <FeatItem color="#00d68f" label="Opportunity scanner" note="Breakouts · Retests · Momentum signals" />
                <FeatItem color="#00d68f" label="Memos & threads — instant" note="No 6-hour delay" />
                <FeatItem color="#00d68f" label="Advanced risk calculator" note="Correlation-aware · Multi-position · Scenario builder" />
                <FeatItem color="#00d68f" label="API access" note="500 calls/day" />
                <FeatItem color="#00d68f" label="90-day historical data" />
                <FeatItem color="#00d68f" label="CSV / PDF export" />
                <FeatItem color="#00d68f" label="Daily email digest" />
              </ul>
            </div>
            <div className="font-mono-cc" style={{ fontSize: 10, color: '#38405a', textAlign: 'center', paddingTop: 14, borderTop: '1px solid #1a2030' }}>No credit card to start trial · Cancel anytime</div>
          </div>
        </div>

        {/* ── PREMIUM+ ── */}
        <div style={{ background: '#10141c', border: '1px solid rgba(155,124,244,0.2)', borderRadius: 8, padding: '28px 24px', display: 'flex', flexDirection: 'column', gap: 20, position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 2, background: 'linear-gradient(90deg, transparent, #9b7cf4, transparent)' }} />
          <div>
            <div className="font-mono-cc" style={{ fontSize: 9, letterSpacing: '2px', textTransform: 'uppercase', color: '#9b7cf4', marginBottom: 4 }}>Command</div>
            <div className="font-bebas" style={{ fontSize: 32, color: '#9b7cf4', lineHeight: 1 }}>Premium+</div>
            <div style={{ display: 'flex', alignItems: 'baseline', gap: 6, marginTop: 6 }}>
              <div className="font-bebas" style={{ fontSize: 44, lineHeight: 1, color: '#e2e6f0' }}>$200</div>
              <div>
                <div className="font-mono-cc" style={{ fontSize: 11, color: '#38405a' }}>/month</div>
                <div className="font-mono-cc" style={{ fontSize: 9, color: '#9b7cf4', marginTop: 1 }}>14-day free trial</div>
              </div>
            </div>
            <div style={{ fontSize: 12, color: '#788098', lineHeight: 1.6 }}>For serious traders and funds. Maximum depth, first-hour signals, custom analysis, and high-volume API.</div>
          </div>
          <button className="font-mono-cc" style={{ width: '100%', textAlign: 'center', fontSize: 11, letterSpacing: '0.8px', textTransform: 'uppercase', padding: 12, borderRadius: 5, color: '#08090c', background: '#9b7cf4', border: 'none', cursor: 'pointer', fontWeight: 500, boxShadow: '0 0 20px rgba(155,124,244,0.25)' }}>
            Start 14-Day Trial Free →
          </button>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10 }}>
            <FeatItem color="#9b7cf4" label="Everything in Premium" />
            <FeatItem color="#9b7cf4" label="First-hour exclusive access" note="Signals before all other tiers" featured />
            <FeatItem color="#9b7cf4" label="Custom analysis requests" note="Request sector deep-dives & asset reports" featured />
            <FeatItem color="#9b7cf4" label="API — unlimited calls/day" />
            <FeatItem color="#9b7cf4" label="Unlimited historical data" />
            <FeatItem color="#9b7cf4" label="Priority support" />
          </ul>
          <div className="font-mono-cc" style={{ fontSize: 10, color: '#38405a', textAlign: 'center', paddingTop: 12, borderTop: '1px solid rgba(155,124,244,0.15)' }}>No credit card to start trial</div>
        </div>
      </div>{/* plans-grid */}
      </div>{/* plans-section */}

      {/* ══ COMPARISON TABLE ══ */}
      <div className="compare-section">
        <div className="font-mono-cc" style={{ fontSize: 10, letterSpacing: '2px', textTransform: 'uppercase', color: '#38405a', marginBottom: 8 }}>Side by side</div>
        <h2 className="font-serif-cc" style={{ fontSize: 32, color: '#e2e6f0', lineHeight: 1.2, letterSpacing: -0.5, marginBottom: 36 }}>
          See what&apos;s <em style={{ fontStyle: 'italic', color: '#00d68f' }}>inside each tier.</em>
        </h2>
        <div className="table-scroll">
        <table style={{ width: '100%', minWidth: 480, borderCollapse: 'collapse', border: '1px solid #1a2030', borderRadius: 8, overflow: 'hidden' }}>
          <thead>
            <tr style={{ background: '#151a26' }}>
              {['Feature', 'Basic', 'Premium', 'Premium+'].map((h, i) => (
                <th key={h} style={{ padding: '14px 20px', textAlign: i === 0 ? 'left' : 'center', fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '1px', textTransform: 'uppercase', color: i === 2 ? '#00d68f' : i === 3 ? '#9b7cf4' : '#38405a', fontWeight: 400, borderBottom: '1px solid #1a2030', ...(i === 2 ? { background: 'rgba(0,214,143,0.04)', borderLeft: '1px solid rgba(0,214,143,0.15)', borderRight: '1px solid rgba(0,214,143,0.15)' } : {}) }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {compareRows.map((row, i) => {
              if ('section' in row) {
                return (
                  <tr key={i}>
                    <td colSpan={4} style={{ padding: '8px 20px', background: '#0c0e12', fontFamily: 'var(--font-mono)', fontSize: 9, letterSpacing: '1.5px', textTransform: 'uppercase', color: '#38405a', borderBottom: '1px solid #1a2030' }}>
                      {row.section}
                    </td>
                  </tr>
                );
              }
              const cell = (v: string, accent: string) => (
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: v === '✓' ? 14 : v === '—' ? 14 : 11, color: v === '✓' ? accent : v === '—' ? '#38405a' : '#788098' }}>{v}</span>
              );
              return (
                <tr key={i} style={{ borderBottom: '1px solid #1a2030' }}>
                  <td style={{ padding: '12px 20px', fontSize: 12.5, color: '#e2e6f0' }}>{row.feat}</td>
                  <td style={{ padding: '12px 20px', textAlign: 'center' }}>{cell(row.basic!, '#00d68f')}</td>
                  <td style={{ padding: '12px 20px', textAlign: 'center', background: 'rgba(0,214,143,0.02)', borderLeft: '1px solid rgba(0,214,143,0.1)', borderRight: '1px solid rgba(0,214,143,0.1)' }}>{cell(row.premium!, '#00d68f')}</td>
                  <td style={{ padding: '12px 20px', textAlign: 'center' }}>{cell(row.plus!, '#9b7cf4')}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
        </div>{/* table-scroll */}
      </div>{/* compare-section */}

      {/* ══ FAQ ══ */}
      <div className="faq-section">
        <div>
          <h2 className="font-serif-cc" style={{ fontSize: 32, color: '#e2e6f0', lineHeight: 1.2, letterSpacing: -0.5, marginBottom: 12 }}>
            Common <em style={{ fontStyle: 'italic', color: '#00d68f' }}>questions.</em>
          </h2>
          <p style={{ fontSize: 13, color: '#38405a', lineHeight: 1.6 }}>Everything you need to know before starting your trial.</p>
        </div>
        <div>
          {faqs.map((faq, i) => (
            <details key={i} style={{ borderTop: '1px solid #1a2030', ...(i === faqs.length - 1 ? { borderBottom: '1px solid #1a2030' } : {}) }}>
              <summary style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '18px 0', gap: 16, cursor: 'pointer', listStyle: 'none' }}>
                <span style={{ fontSize: 13, fontWeight: 500, color: '#e2e6f0', lineHeight: 1.4 }}>{faq.q}</span>
                <span className="font-mono-cc" style={{ fontSize: 10, color: '#38405a', flexShrink: 0 }}>+</span>
              </summary>
              <p style={{ fontSize: 12.5, color: '#788098', lineHeight: 1.7, paddingBottom: 18 }}>{faq.a}</p>
            </details>
          ))}
        </div>
      </div>

      {/* ══ BOTTOM CTA ══ */}
      <div className="pricing-cta-wrap">
        <div style={{ background: '#10141c', border: '1px solid #222c42', borderRadius: 10, padding: 60, textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 60% 50% at 50% 0%, rgba(0,214,143,0.06) 0%, transparent 70%)', pointerEvents: 'none' }} />
          <div style={{ position: 'absolute', top: 0, left: '20%', right: '20%', height: 1, background: 'linear-gradient(90deg, transparent, #00d68f, transparent)' }} />
          <h2 className="font-serif-cc" style={{ fontSize: 36, color: '#e2e6f0', lineHeight: 1.2, letterSpacing: -0.5, marginBottom: 12 }}>
            The cockpit is ready.<br /><em style={{ fontStyle: 'italic', color: '#00d68f' }}>Are you?</em>
          </h2>
          <p style={{ fontSize: 14, color: '#788098', maxWidth: 420, margin: '0 auto 28px', lineHeight: 1.7 }}>
            Start with any trial. No credit card. No commitment. Cancel anytime.
          </p>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center' }}>
            <Link href="/auth/register" className="font-mono-cc" style={{ padding: '14px 32px', borderRadius: 5, color: '#08090c', background: '#00d68f', fontWeight: 500, fontSize: 11, letterSpacing: '0.8px', textTransform: 'uppercase', textDecoration: 'none', boxShadow: '0 0 24px rgba(0,214,143,0.25)' }}>
              Start Free Trial →
            </Link>
            <Link href="/auth/login" className="font-mono-cc" style={{ padding: '13px 24px', borderRadius: 5, color: '#788098', background: 'none', border: '1px solid #222c42', fontSize: 11, letterSpacing: '0.8px', textTransform: 'uppercase', textDecoration: 'none' }}>
              Sign In
            </Link>
          </div>
          <p className="font-mono-cc" style={{ fontSize: 10, color: '#38405a', marginTop: 14 }}>340+ traders on the waitlist · 47 beta spots remain</p>
        </div>
      </div>

    </div>
  );
}
