import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Pricing',
  description: 'Crevia Analytics pricing plans — Free, Pro, and Enterprise.',
};

const tiers = [
  {
    name: 'Free',
    price: '$0',
    period: 'forever',
    description: 'Delayed access to BTC and ETH analysis.',
    features: [
      'BTC & ETH analysis (6-hour delay)',
      'Market dashboard',
      'Weekly email digest',
      'Community access',
    ],
    cta: 'Get Started',
    ctaHref: '/analysis',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '$19',
    period: '/month',
    description: 'Real-time access to all 16 assets with API access.',
    features: [
      'All 16 assets — real-time',
      'Market memos & threads instantly',
      'Risk alerts',
      'Daily email digest',
      'API access (100 calls/day)',
      '30-day historical data',
      'CSV/PDF export',
    ],
    cta: 'Subscribe to Pro',
    ctaHref: '#',
    highlight: true,
  },
  {
    name: 'Enterprise',
    price: '$99',
    period: '/month',
    description: 'Full platform access with high-volume API and custom alerts.',
    features: [
      'Everything in Pro',
      'First-hour exclusive access',
      'Custom asset alerts',
      'API access (10,000 calls/day)',
      'Unlimited historical data',
      'Priority support',
      'Custom analysis requests',
    ],
    cta: 'Contact Us',
    ctaHref: '#',
    highlight: false,
  },
];

export default function PricingPage() {
  return (
    <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6">
      {/* Header */}
      <div className="text-center">
        <h1 className="text-4xl font-bold text-white">Simple, transparent pricing</h1>
        <p className="mt-4 text-lg text-zinc-400">
          All analysis becomes free after 6 hours. Pay for speed, not access.
        </p>
      </div>

      {/* Pricing Cards */}
      <div className="mt-12 grid gap-6 md:grid-cols-3">
        {tiers.map((tier) => (
          <div
            key={tier.name}
            className={`rounded-2xl border p-8 ${
              tier.highlight
                ? 'border-emerald-500/50 bg-emerald-500/5 ring-1 ring-emerald-500/20'
                : 'border-zinc-800 bg-zinc-900/30'
            }`}
          >
            {tier.highlight && (
              <span className="inline-block rounded-full bg-emerald-500/20 px-3 py-1 text-xs font-semibold text-emerald-400 mb-4">
                Most Popular
              </span>
            )}
            <h3 className="text-xl font-bold text-white">{tier.name}</h3>
            <div className="mt-3 flex items-baseline gap-1">
              <span className="text-4xl font-bold text-white">{tier.price}</span>
              <span className="text-zinc-500">{tier.period}</span>
            </div>
            <p className="mt-3 text-sm text-zinc-400">{tier.description}</p>

            <Link
              href={tier.ctaHref}
              className={`mt-6 block rounded-lg py-2.5 text-center text-sm font-semibold transition-colors ${
                tier.highlight
                  ? 'bg-emerald-500 text-zinc-950 hover:bg-emerald-400'
                  : 'border border-zinc-700 text-zinc-300 hover:border-zinc-600 hover:bg-zinc-900'
              }`}
            >
              {tier.cta}
            </Link>

            <ul className="mt-8 space-y-3">
              {tier.features.map((feature) => (
                <li key={feature} className="flex items-start gap-2 text-sm text-zinc-300">
                  <svg className="mt-0.5 h-4 w-4 flex-shrink-0 text-emerald-500" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                  </svg>
                  {feature}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {/* FAQ-style section */}
      <div className="mt-16 rounded-2xl border border-zinc-800 bg-zinc-900/30 p-8">
        <h2 className="text-xl font-bold text-white">How the free tier works</h2>
        <p className="mt-3 text-zinc-400">
          Every piece of analysis generated by Crevia Analytics becomes free to read after 6 hours.
          This means Google indexes all our content (great for you — more analysis to discover),
          while Pro and Enterprise subscribers get a head start with real-time access.
        </p>
        <p className="mt-3 text-zinc-400">
          Pro subscribers get instant access to all 16 tracked assets including majors (BTC, ETH, SOL, BNB),
          memecoins (DOGE, SHIB, PEPE, FLOKI), privacy coins (XMR, ZEC, DASH, SCRT),
          and DeFi protocols (AAVE, UNI, CRV, LDO).
        </p>
      </div>
    </div>
  );
}
