"""
DocxFormatter — Convert ContentSession output into a formatted Word document.

Takes the master brief generated by ContentSession and writes a .docx file
with proper styles: headings, bold/italic inline, bullet lists, metadata footer.

Usage:
    from src.utils.docx_formatter import DocxFormatter

    formatter = DocxFormatter()
    path = formatter.write(master_brief, output_dir="output/newsletters")
    # path → "output/newsletters/2026-02-28_morning_scan.docx"
"""

import os
import re
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)


class DocxFormatter:
    """Converts a ContentSession master brief into a formatted .docx file."""

    # Brand colours (RGB tuples)
    COLOR_HEADLINE  = "10B981"   # emerald green  — used for H1
    COLOR_SECTION   = "1F2937"   # near-black     — H2 / H3
    COLOR_ACCENT    = "6EE7B7"   # light green    — callout labels
    COLOR_FOOTER    = "6B7280"   # muted grey     — footer / metadata

    # Font choices
    FONT_HEADING = "Bebas Neue"   # falls back to Arial if not installed
    FONT_BODY    = "Calibri"

    def __init__(self, output_dir: str = "output/newsletters"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ── Public ────────────────────────────────────────────────────────────────

    def write(
        self,
        master: Dict[str, Any],
        mode: str = "morning_scan",
        output_path: Optional[str] = None,
    ) -> str:
        """
        Build a .docx from a ContentSession master brief.

        Args:
            master:      The dict returned by ContentSession._get_master()
            mode:        'morning_scan' | 'mid_day_update' | 'closing_bell' | 'breaking_news'
            output_path: Override the default output path (full .docx path)

        Returns:
            Absolute path to the written .docx file.
        """
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches, Cm
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()
        self._configure_page(doc)
        self._configure_styles(doc)

        headline    = master.get("headline", "Crypto Market Analysis")
        narrative   = master.get("narrative", "")
        signal      = master.get("directional_signal", "NEUTRAL")
        assets      = master.get("mentioned_assets", [])
        tags        = master.get("tags", [])
        key_insight = master.get("key_insight", "")

        now      = datetime.now(timezone.utc)
        date_str = now.strftime("%B %d, %Y")
        time_str = now.strftime("%H:%M UTC")

        # ── Cover block ───────────────────────────────────────────────────────
        self._add_cover(doc, headline, mode, date_str, time_str, signal)

        # ── Key insight callout ───────────────────────────────────────────────
        if key_insight:
            self._add_callout(doc, key_insight)

        # ── Narrative body ────────────────────────────────────────────────────
        self._parse_markdown(doc, narrative)

        # ── Metadata footer ───────────────────────────────────────────────────
        self._add_footer_block(doc, assets, tags, date_str, time_str)

        # ── Save ──────────────────────────────────────────────────────────────
        if output_path:
            path = Path(output_path)
        else:
            slug = now.strftime("%Y-%m-%d") + f"_{mode}"
            path = self.output_dir / f"{slug}.docx"

        doc.save(str(path))
        logger.info(f"[DocxFormatter] Saved → {path}")
        return str(path.resolve())

    # ── Document setup ────────────────────────────────────────────────────────

    def _configure_page(self, doc):
        from docx.shared import Inches
        section = doc.sections[0]
        section.page_width  = Inches(8.5)
        section.page_height = Inches(11)
        section.left_margin   = Inches(1.2)
        section.right_margin  = Inches(1.2)
        section.top_margin    = Inches(1.0)
        section.bottom_margin = Inches(1.0)

    def _configure_styles(self, doc):
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        normal = doc.styles["Normal"]
        normal.font.name = self.FONT_BODY
        normal.font.size = Pt(11)

        for h_name, size, color_hex, bold in [
            ("Heading 1", 26, self.COLOR_HEADLINE, True),
            ("Heading 2", 16, self.COLOR_SECTION,  True),
            ("Heading 3", 13, self.COLOR_SECTION,  True),
        ]:
            try:
                style = doc.styles[h_name]
            except KeyError:
                style = doc.styles.add_style(h_name, 1)  # 1 = paragraph
            style.font.name  = self.FONT_HEADING
            style.font.size  = Pt(size)
            style.font.bold  = bold
            r, g, b = self._hex_to_rgb(color_hex)
            style.font.color.rgb = RGBColor(r, g, b)
            style.paragraph_format.space_before = Pt(14)
            style.paragraph_format.space_after  = Pt(4)

    # ── Cover block ───────────────────────────────────────────────────────────

    def _add_cover(self, doc, headline, mode, date_str, time_str, signal):
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        mode_label = {
            "morning_scan":   "MORNING SCAN",
            "mid_day_update": "MID-DAY UPDATE",
            "closing_bell":   "CLOSING BELL",
            "breaking_news":  "BREAKING NEWS",
        }.get(mode, mode.upper().replace("_", " "))

        # Mode label (small caps green)
        label_p = doc.add_paragraph()
        label_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = label_p.add_run(f"CREVIACOCKPIT  ·  {mode_label}  ·  {date_str}  ·  {time_str}")
        run.font.size = Pt(9)
        r, g, b = self._hex_to_rgb(self.COLOR_ACCENT)
        run.font.color.rgb = RGBColor(r, g, b)
        run.font.name = self.FONT_BODY

        # Headline
        h_para = doc.add_paragraph(style="Heading 1")
        h_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
        h_para.add_run(headline)

        # Signal pill line
        signal_color = {
            "BULLISH":     "10B981",
            "BEARISH":     "EF4444",
            "NEUTRAL":     "6B7280",
            "RANGE_BOUND": "F59E0B",
        }.get(signal, "6B7280")

        sig_p = doc.add_paragraph()
        sig_run = sig_p.add_run(f"  {signal}  ")
        sig_run.font.bold = True
        sig_run.font.size = Pt(10)
        r, g, b = self._hex_to_rgb(signal_color)
        sig_run.font.color.rgb = RGBColor(r, g, b)
        sig_run.font.name = self.FONT_BODY

        # Divider (thin horizontal rule via bottom border on paragraph)
        div_p = doc.add_paragraph()
        self._add_bottom_border(div_p, color=self.COLOR_HEADLINE)
        div_p.paragraph_format.space_after  = Pt(12)
        div_p.paragraph_format.space_before = Pt(4)

    # ── Callout box ───────────────────────────────────────────────────────────

    def _add_callout(self, doc, text: str):
        from docx.shared import Pt, RGBColor
        from docx.oxml.ns import qn
        from docx.oxml   import OxmlElement

        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(8)
        p.paragraph_format.space_after  = Pt(12)
        p.paragraph_format.left_indent  = Pt(24)

        label_run = p.add_run("KEY INSIGHT   ")
        label_run.font.bold = True
        label_run.font.size = Pt(9)
        r, g, b = self._hex_to_rgb(self.COLOR_ACCENT)
        label_run.font.color.rgb = RGBColor(r, g, b)
        label_run.font.name = self.FONT_BODY

        body_run = p.add_run(text)
        body_run.font.size = Pt(11)
        body_run.font.italic = True
        body_run.font.name = self.FONT_BODY

        # Left border (green stripe)
        pPr = p._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        left = OxmlElement("w:left")
        left.set(qn("w:val"),   "single")
        left.set(qn("w:sz"),    "12")
        left.set(qn("w:space"), "12")
        left.set(qn("w:color"), self.COLOR_HEADLINE)
        pBdr.append(left)
        pPr.append(pBdr)

    # ── Markdown parser ───────────────────────────────────────────────────────

    def _parse_markdown(self, doc, markdown: str):
        """
        Light markdown → docx paragraph conversion.
        Handles: # H1, ## H2, ### H3, - bullet, **bold**, *italic*, blank lines.
        """
        lines = markdown.splitlines()
        i = 0
        while i < len(lines):
            line = lines[i]
            stripped = line.strip()
            i += 1

            if not stripped:
                continue

            # Headings
            if stripped.startswith("### "):
                p = doc.add_paragraph(style="Heading 3")
                self._inline(p, stripped[4:])

            elif stripped.startswith("## "):
                p = doc.add_paragraph(style="Heading 2")
                self._inline(p, stripped[3:])

            elif stripped.startswith("# "):
                p = doc.add_paragraph(style="Heading 1")
                self._inline(p, stripped[2:])

            # Bullet / unordered list
            elif stripped.startswith(("- ", "* ", "• ")):
                p = doc.add_paragraph(style="List Bullet")
                self._inline(p, stripped[2:])

            # Numbered list  (1. text)
            elif re.match(r"^\d+[\.\)]\s", stripped):
                p = doc.add_paragraph(style="List Number")
                self._inline(p, re.sub(r"^\d+[\.\)]\s", "", stripped))

            # Horizontal rule — render as spacing
            elif stripped in ("---", "***", "___"):
                doc.add_paragraph()

            # Normal paragraph
            else:
                from docx.shared import Pt
                p = doc.add_paragraph()
                p.paragraph_format.space_after = Pt(6)
                self._inline(p, stripped)

    def _inline(self, paragraph, text: str):
        """
        Parse inline markdown within a line and add runs with formatting.
        Supports: **bold**, *italic*, `code`, plain text.
        """
        from docx.shared import Pt, RGBColor  # noqa: F401

        # Pattern to split on bold/italic/code markers
        token_re = re.compile(r"(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)")
        parts = token_re.split(text)

        for part in parts:
            if not part:
                continue
            run = paragraph.add_run()
            run.font.name = self.FONT_BODY

            if part.startswith("**") and part.endswith("**"):
                run.text = part[2:-2]
                run.bold = True

            elif part.startswith("*") and part.endswith("*"):
                run.text = part[1:-1]
                run.italic = True

            elif part.startswith("`") and part.endswith("`"):
                run.text = part[1:-1]
                run.font.name = "Courier New"
                run.font.size = Pt(10)
                r, g, b = self._hex_to_rgb(self.COLOR_ACCENT)
                run.font.color.rgb = RGBColor(r, g, b)

            else:
                run.text = part

    # ── Footer metadata ───────────────────────────────────────────────────────

    def _add_footer_block(self, doc, assets, tags, date_str, time_str):
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        # Divider
        div_p = doc.add_paragraph()
        self._add_bottom_border(div_p, color="D1FAE5")
        div_p.paragraph_format.space_before = Pt(24)
        div_p.paragraph_format.space_after  = Pt(8)

        meta_lines = []
        if assets:
            meta_lines.append(f"Assets covered: {', '.join(assets)}")
        if tags:
            meta_lines.append(f"Tags: {', '.join('#' + t for t in tags)}")
        meta_lines.append(f"Generated: {date_str} at {time_str} UTC by CreviaCockpit")
        meta_lines.append("https://creviacockpit.com")

        for line in meta_lines:
            p = doc.add_paragraph(line)
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            p.paragraph_format.space_before = Pt(0)
            p.paragraph_format.space_after  = Pt(2)
            for run in p.runs:
                run.font.size = Pt(9)
                run.font.name = self.FONT_BODY
                r, g, b = self._hex_to_rgb(self.COLOR_FOOTER)
                run.font.color.rgb = RGBColor(r, g, b)

    # ── Utilities ─────────────────────────────────────────────────────────────

    @staticmethod
    def _hex_to_rgb(hex_color: str):
        h = hex_color.lstrip("#")
        return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

    @staticmethod
    def _add_bottom_border(paragraph, color: str = "10B981"):
        from docx.oxml.ns import qn
        from docx.oxml   import OxmlElement
        pPr = paragraph._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"),   "single")
        bottom.set(qn("w:sz"),    "4")
        bottom.set(qn("w:space"), "1")
        bottom.set(qn("w:color"), color)
        pBdr.append(bottom)
        pPr.append(pBdr)
